# Generated by Django 5.0 on 2024-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('est_time_needed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Outpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpost_name', models.CharField(default='Name', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.PositiveIntegerField(default=1)),
                ('premise', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
